import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const typestarOCR = localFont({
  src: '../fonts/Typestar-OCR.woff2', 
  display: 'swap',
  variable: '--font-typestar-ocr',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${typestarOCR.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
